### ISSUE TITLE
x is not in the dataset registry

### ISSUE THREAD

**Issue by MrXujx** [I2-Multimedia-Lab/ProxyFormer#4]
你好，同学，我使用了以下命令
bash ./scripts/test.sh 0 \
    --ckpts ./pretrained/ckpt-best.pth \
    --config ./cfgs/ShapeNet55_models/our_model.yaml \
    --mode easy \
    --exp_name example
    但是它报is not in the dataset registry的错误，应该如何规避呢？
    期待并感谢你的回答。

**Comment by xinpuliu** [comment]
你好 您这个问题怎么解决的呀？
